const menu = {
    list() {
        return [
    {
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"管理员管理",
                        "menuJump":"列表",
                        "tableName":"users"
                    }
                ],
                "menu":"管理员管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"公告类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryGonggao"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"监控节点类型",
                        "menuJump":"列表",
                        "tableName":"dictionaryJiankongjiedian"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"农事安排类型",
                        "menuJump":"列表",
                        "tableName":"dictionaryNongshianpai"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"农作物类型",
                        "menuJump":"列表",
                        "tableName":"dictionaryNongzuowu"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"气象数据类型",
                        "menuJump":"列表",
                        "tableName":"dictionaryQixiangshuju"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"商品类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryShangpin"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"土地类型管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryTudi"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"选苗育种类型",
                        "menuJump":"列表",
                        "tableName":"dictionaryXuanmiaoyuzhong"
                    }
                ],
                "menu":"基础数据管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"公告信息管理",
                        "menuJump":"列表",
                        "tableName":"gonggao"
                    }
                ],
                "menu":"公告信息管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "报表",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"商品管理",
                        "menuJump":"列表",
                        "tableName":"shangpin"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"商品评价管理",
                        "menuJump":"列表",
                        "tableName":"shangpinCommentback"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"商品收藏",
                        "menuJump":"列表",
                        "tableName":"shangpinCollection"
                    }
                    ,
                    {
                        "buttons":[
                            "订单",
                            "报表",
                            "查看",
                            "删除"
                        ],
                        "menu":"商品订单管理",
                        "menuJump":"列表",
                        "tableName":"shangpinOrder"
                    }
                ],
                "menu":"商品管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "报表",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"土地规划管理",
                        "menuJump":"列表",
                        "tableName":"tudi"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"土地留言管理",
                        "menuJump":"列表",
                        "tableName":"tudiLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"土地规划收藏",
                        "menuJump":"列表",
                        "tableName":"tudiCollection"
                    }
                ],
                "menu":"土地规划管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "报表",
                            "修改",
                            "删除"
                        ],
                        "menu":"农作物管理",
                        "menuJump":"列表",
                        "tableName":"nongzuowu"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"农作物留言管理",
                        "menuJump":"列表",
                        "tableName":"nongzuowuLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"农作物收藏",
                        "menuJump":"列表",
                        "tableName":"nongzuowuCollection"
                    }
                ],
                "menu":"农作物管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"农事安排管理",
                        "menuJump":"列表",
                        "tableName":"nongshianpai"
                    }
                ],
                "menu":"农事安排管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"选苗育种管理",
                        "menuJump":"列表",
                        "tableName":"xuanmiaoyuzhong"
                    }
                ],
                "menu":"选苗育种管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"气象数据管理",
                        "menuJump":"列表",
                        "tableName":"qixiangshuju"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"气象数据留言",
                        "menuJump":"列表",
                        "tableName":"qixiangshujuLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "删除"
                        ],
                        "menu":"气象数据收藏",
                        "menuJump":"列表",
                        "tableName":"qixiangshujuCollection"
                    }
                ],
                "menu":"气象数据管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"监控节点管理",
                        "menuJump":"列表",
                        "tableName":"jiankongjiedian"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"监控记录管理",
                        "menuJump":"列表",
                        "tableName":"jiankongjiedianJilu"
                    }
                ],
                "menu":"监控节点管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"用户管理",
                        "menuJump":"列表",
                        "tableName":"yonghu"
                    }
                ],
                "menu":"用户管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"员工管理",
                        "menuJump":"列表",
                        "tableName":"yuangong"
                    }
                ],
                "menu":"员工管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"轮播图管理",
                        "menuJump":"列表",
                        "tableName":"config"
                    }
                ],
                "menu":"轮播图信息"
            }
        ],
        "frontMenu":[],
        "hasBackLogin":"是",
        "hasBackRegister":"否",
        "hasFrontLogin":"否",
        "hasFrontRegister":"否",
        "roleName":"管理员",
        "tableName":"users"
    }
    ,
            {
                "backMenu":[
                    {
                        "child":[
                            {
                                "buttons":[
                                    "查看"
                                ],
                                "menu":"公告信息管理",
                                "menuJump":"列表",
                                "tableName":"gonggao"
                            }
                        ],
                        "menu":"公告信息管理"
                    }
                    ,{
                        "child":[
                            {
                                "buttons":[
                                    "查看"
                                ],
                                "menu":"商品管理",
                                "menuJump":"列表",
                                "tableName":"shangpin"
                            }
                            ,
                            {
                                "buttons":[
                                    "查看"
                                ],
                                "menu":"商品评价管理",
                                "menuJump":"列表",
                                "tableName":"shangpinCommentback"
                            }
                            ,
                            {
                                "buttons":[
                                    "查看",
                                    "订单"
                                ],
                                "menu":"商品订单管理",
                                "menuJump":"列表",
                                "tableName":"shangpinOrder"
                            }
                        ],
                        "menu":"商品管理"
                    }
                    ,{
                        "child":[
                            {
                                "buttons":[
                                    "查看"
                                ],
                                "menu":"土地规划管理",
                                "menuJump":"列表",
                                "tableName":"tudi"
                            }
                        ],
                        "menu":"土地规划管理"
                    }
                    ,{
                        "child":[
                            {
                                "buttons":[
                                    "查看",
                                    "新增"
                                ],
                                "menu":"农作物管理",
                                "menuJump":"列表",
                                "tableName":"nongzuowu"
                            }
                        ],
                        "menu":"农作物管理"
                    }
                    ,{
                        "child":[
                            {
                                "buttons":[
                                    "查看"
                                ],
                                "menu":"农事安排管理",
                                "menuJump":"列表",
                                "tableName":"nongshianpai"
                            }
                        ],
                        "menu":"农事安排管理"
                    }
                    ,{
                        "child":[
                            {
                                "buttons":[
                                    "查看",
                                    "新增"
                                ],
                                "menu":"选苗育种管理",
                                "menuJump":"列表",
                                "tableName":"xuanmiaoyuzhong"
                            }
                        ],
                        "menu":"选苗育种管理"
                    }
                    ,{
                        "child":[
                            {
                                "buttons":[
                                    "查看",
                                    "新增"
                                ],
                                "menu":"气象数据管理",
                                "menuJump":"列表",
                                "tableName":"qixiangshuju"
                            }
                        ],
                        "menu":"气象数据管理"
                    }
                    ,{
                        "child":[
                            {
                                "buttons":[
                                    "查看"
                                ],
                                "menu":"监控节点管理",
                                "menuJump":"列表",
                                "tableName":"jiankongjiedian"
                            }
                            ,
                            {
                                "buttons":[
                                    "查看",
                                    "新增",
                                    "删除"
                                ],
                                "menu":"监控记录管理",
                                "menuJump":"列表",
                                "tableName":"jiankongjiedianJilu"
                            }
                        ],
                        "menu":"监控节点管理"
                    }
                ],
                "frontMenu":[],
                "hasBackLogin":"是",
                "hasBackRegister":"否",
                "hasFrontLogin":"否",
                "hasFrontRegister":"否",
                "roleName":"员工",
                "tableName":"yuangong"
            }
]
    }
}
export default menu;
